Repository secretlint/secretlint, pull requests merged in 2023-12, with the labels that each got.

#717 Fix Full Changelog URL for release information
  .github/workflows/create-release-pr.yml
Labels: Type: CI

#721 feat(1password): add 1Password rule
  packages/@secretlint/secretlint-rule-1password/LICENSE
  packages/@secretlint/secretlint-rule-1password/README.md
  packages/@secretlint/secretlint-rule-1password/package.json
  packages/@secretlint/secretlint-rule-1password/src/index.ts
  packages/@secretlint/secretlint-rule-1password/test/index.test.ts
  packages/@secretlint/secretlint-rule-1password/test/snapshots/ng.secret/input.txt
  packages/@secretlint/secretlint-rule-1password/test/snapshots/ng.secret/output.json
  packages/@secretlint/secretlint-rule-1password/test/snapshots/ok.ops_prefix_but_is_not_jwt/input.txt
  packages/@secretlint/secretlint-rule-1password/test/snapshots/ok.ops_prefix_but_is_not_jwt/output.json
  packages/@secretlint/secretlint-rule-1password/test/snapshots/ok.valid/input.txt
  packages/@secretlint/secretlint-rule-1password/test/snapshots/ok.valid/output.json
  packages/@secretlint/secretlint-rule-1password/tsconfig.json
Labels: Type: New Rule

#702 docs: Add OpenAI
  README.md
Labels: Type: Documentation
