Repository secretlint/secretlint, pull requests merged in 2023-07, with the labels that each got.

#532 fix(turbo): add $schema
  turbo.json
Labels: Type: Meta

#538 perf: output target is ES2022
  .github/workflows/publish.yml
  .github/workflows/test.yml
  README.md
  examples/benchmark/targets/js-primer/tools/applescript/tsconfig.json
  packages/@secretlint/config-creator/tsconfig.json
  packages/@secretlint/config-loader/tsconfig.json
  packages/@secretlint/core/tsconfig.json
  packages/@secretlint/formatter/tsconfig.json
  packages/@secretlint/messages-to-markdown/tsconfig.json
  packages/@secretlint/node/tsconfig.json
  packages/@secretlint/profiler/tsconfig.json
  packages/@secretlint/quick-start/tsconfig.json
  packages/@secretlint/secretlint-formatter-sarif/tsconfig.json
  packages/@secretlint/secretlint-rule-aws/tsconfig.json
  packages/@secretlint/secretlint-rule-azure/tsconfig.json
  packages/@secretlint/secretlint-rule-basicauth/tsconfig.json
  packages/@secretlint/secretlint-rule-example/tsconfig.json
  packages/@secretlint/secretlint-rule-filter-comments/tsconfig.json
  packages/@secretlint/secretlint-rule-gcp/tsconfig.json
  packages/@secretlint/secretlint-rule-github/tsconfig.json
  packages/@secretlint/secretlint-rule-internal-test-cjs/tsconfig.json
  packages/@secretlint/secretlint-rule-internal-test-esm/tsconfig.json
  packages/@secretlint/secretlint-rule-no-dotenv/tsconfig.json
  packages/@secretlint/secretlint-rule-no-homedir/tsconfig.json
  packages/@secretlint/secretlint-rule-no-k8s-kind-secret/tsconfig.json
  packages/@secretlint/secretlint-rule-npm/tsconfig.json
  packages/@secretlint/secretlint-rule-pattern/tsconfig.json
  packages/@secretlint/secretlint-rule-preset-canary/tsconfig.json
  packages/@secretlint/secretlint-rule-preset-recommend/tsconfig.json
  packages/@secretlint/secretlint-rule-privatekey/tsconfig.json
  packages/@secretlint/secretlint-rule-secp256k1-privatekey/tsconfig.json
  packages/@secretlint/secretlint-rule-sendgrid/tsconfig.json
  packages/@secretlint/secretlint-rule-shopify/tsconfig.json
  packages/@secretlint/secretlint-rule-slack/tsconfig.json
  packages/@secretlint/source-creator/tsconfig.json
  packages/@secretlint/tester/tsconfig.json
  packages/@secretlint/types/tsconfig.json
  packages/secretlint/tsconfig.json
  publish/binary-compiler/tsconfig.json
  tsconfig.json
Labels: Type: Breaking Change

#542 docs: Update rule document
  docs/secretlint-rule.md
  packages/@secretlint/core/test/fixtures/secretlint-rule-example.ts
  packages/@secretlint/messages-to-markdown/test/example-rule.ts
  packages/@secretlint/secretlint-rule-aws/test/index.test.ts
  packages/@secretlint/secretlint-rule-azure/test/index.test.ts
  packages/@secretlint/secretlint-rule-basicauth/test/index.test.ts
  packages/@secretlint/secretlint-rule-example/src/index.ts
  packages/@secretlint/secretlint-rule-example/test/index.test.ts
  packages/@secretlint/secretlint-rule-filter-comments/src/index.ts
  packages/@secretlint/secretlint-rule-filter-comments/test/index.test.ts
  packages/@secretlint/secretlint-rule-gcp/test/index.test.ts
  packages/@secretlint/secretlint-rule-github/test/index.test.ts
  packages/@secretlint/secretlint-rule-internal-test-cjs/src/index.ts
  packages/@secretlint/secretlint-rule-internal-test-esm/src/index.ts
  packages/@secretlint/secretlint-rule-no-dotenv/src/index.ts
  packages/@secretlint/secretlint-rule-no-dotenv/test/index.test.ts
  packages/@secretlint/secretlint-rule-no-homedir/test/index.test.ts
  packages/@secretlint/secretlint-rule-no-k8s-kind-secret/test/index.test.ts
  packages/@secretlint/secretlint-rule-npm/test/index.test.ts
  packages/@secretlint/secretlint-rule-pattern/test/index.test.ts
  packages/@secretlint/secretlint-rule-preset-canary/test/index.test.ts
  packages/@secretlint/secretlint-rule-privatekey/test/index.test.ts
  packages/@secretlint/secretlint-rule-secp256k1-privatekey/src/index.ts
  packages/@secretlint/secretlint-rule-secp256k1-privatekey/test/index.test.ts
  packages/@secretlint/secretlint-rule-sendgrid/test/index.test.ts
  packages/@secretlint/secretlint-rule-shopify/test/index.test.ts
  packages/@secretlint/secretlint-rule-slack/test/index.test.ts
  packages/@secretlint/tester/src/index.ts
  packages/@secretlint/tester/test/fixtures/secretlint-rule-example.ts
  packages/@secretlint/tester/test/index.test.ts
Labels: Type: Documentation

#544 fix(core): update structured-source@4
  .mocharc.json
  packages/@secretlint/core/package.json
  packages/@secretlint/core/src/SecretLintSourceCodeImpl.ts
  yarn.lock
Labels: Type: Dependencies

#545 fix(no-homedir): add @textlint/regexp-string-matcher as deps
  packages/@secretlint/core/src/index.ts
  packages/@secretlint/secretlint-rule-no-homedir/package.json
Labels: Type: Bug

#547 fix(secretlint): update meow and globby and exit status
  README.md
  packages/@secretlint/messages-to-markdown/package.json
  packages/@secretlint/messages-to-markdown/src/cli.ts
  packages/secretlint/README.md
  packages/secretlint/bin/secretlint.js
  packages/secretlint/package.json
  packages/secretlint/src/cli.ts
  packages/secretlint/src/create-secretlintrc.ts
  packages/secretlint/src/index.ts
  packages/secretlint/src/search.ts
  packages/secretlint/test/snapshots/--output=out.txt/.secretlintrc.json
  packages/secretlint/test/snapshots/--output=out.txt/input.txt
  packages/secretlint/test/snapshots/--output=out.txt/options.ts
  packages/secretlint/test/snapshots/--output=out.txt/output.json
  yarn.lock
Labels: Type: Breaking Change

#549 chore(deps): update to lerna-lite v2
  package.json
  packages/@secretlint/secretlint-rule-preset-canary/package.json
  packages/@secretlint/secretlint-rule-preset-recommend/package.json
  yarn.lock
Labels: Type: Dependencies

#553 fix: fix weak regex pattern
  packages/@secretlint/secretlint-rule-gcp/src/index.ts
  packages/@secretlint/secretlint-rule-npm/src/index.ts
Labels: Type: Bug

#555 fix(quick-start): add the config directory to the install file list
  packages/@secretlint/quick-start/package.json
Labels: Type: Bug

#557 fix(quick start): exit status align to secretlint command
  packages/@secretlint/quick-start/bin/quick-start.js
Labels: Type: Bug

#559 test: add stdout test
  examples/cli/package.json
  yarn.lock
Labels: Type: Testing

#564 test: add test for @secretlint/quick-start
  examples/quick-start/LICENSE
  examples/quick-start/README.md
  examples/quick-start/credential
  examples/quick-start/package.json
  examples/quick-start/secret.key
  packages/@secretlint/secretlint-rule-preset-recommend/package.json
Labels: Type: Testing

#563 fix: use fileURLToPath for mimicked __dirname
  packages/@secretlint/config-creator/test/index.test.ts
  packages/@secretlint/config-loader/test/index.test.ts
  packages/@secretlint/config-loader/test/snapshot.test.ts
  packages/@secretlint/formatter/src/index.ts
  packages/@secretlint/formatter/test/index.test.ts
  packages/@secretlint/formatter/test/snapshots/input.ts
  packages/@secretlint/node/test/index.test.ts
  packages/@secretlint/quick-start/src/index.ts
  packages/@secretlint/secretlint-formatter-sarif/test/index.test.ts
  packages/@secretlint/secretlint-formatter-sarif/test/snapshots/input.ts
  packages/@secretlint/secretlint-rule-preset-recommend/import-tests.js
  packages/@secretlint/secretlint-rule-preset-recommend/test/index.test.ts
  packages/@secretlint/source-creator/test/index.test.ts
Labels: Type: Bug
