Repository secretlint/secretlint, pull requests merged in 2023-02, with the labels that each got.

#387 feat(Dockerfile): install secretlint-rule-pattern
  publish/docker/Dockerfile
Labels: Type: Feature

#390 CI: use new release flow based on GitHub Release
  .github/release.yml
  .github/workflows/create-release-force-patch-pr.yml
  .github/workflows/create-release-pr.yml
  .github/workflows/publish.yml
  package.json
Labels: Type: Release

#393 docs(docker): add built-in packages
  publish/docker/README.md
Labels: Type: Documentation

#394 docs: Update README
  README.md
Labels: Type: Documentation

#395 CI: ::set-output is drepecated
  .github/workflows/publish.yml
Labels: Type: CI

#396 Simple detection of common Azure and Azure AD secrets
  packages/@secretlint/secretlint-rule-azure/.mocharc.json
  packages/@secretlint/secretlint-rule-azure/LICENSE
  packages/@secretlint/secretlint-rule-azure/README.md
  packages/@secretlint/secretlint-rule-azure/package.json
  packages/@secretlint/secretlint-rule-azure/src/index.ts
  packages/@secretlint/secretlint-rule-azure/test/index.test.ts
  packages/@secretlint/secretlint-rule-azure/test/snapshots/ng.ad_tenant_id/input
  packages/@secretlint/secretlint-rule-azure/test/snapshots/ng.ad_tenant_id/output.json
  packages/@secretlint/secretlint-rule-azure/test/snapshots/ng.azure_client_id/input
  packages/@secretlint/secretlint-rule-azure/test/snapshots/ng.azure_client_id/output.json
  packages/@secretlint/secretlint-rule-azure/test/snapshots/ng.azure_client_secret/input
  packages/@secretlint/secretlint-rule-azure/test/snapshots/ng.azure_client_secret/output.json
  packages/@secretlint/secretlint-rule-azure/test/tsconfig.json
  packages/@secretlint/secretlint-rule-azure/tsconfig.json
Labels: Type: Feature, Type: New Rule

#403 docs: Update Release Flow
  CONTRIBUTING.md
Labels: Type: Documentation

#405 feat(canary): add "browser" build experimental
  .gitignore
  packages/@secretlint/secretlint-rule-preset-canary/package.json
  packages/@secretlint/secretlint-rule-preset-canary/rollup.config.mjs
  yarn.lock
Labels: Type: Feature

#408 fix(canary): remove `process.platform` from browser bundle
  packages/@secretlint/secretlint-rule-preset-canary/package.json
  packages/@secretlint/secretlint-rule-preset-canary/rollup.config.mjs
  yarn.lock
Labels: Type: Bug

#410 refactor(core): remove "events" and "assert" from core
  packages/@secretlint/core/package.json
  packages/@secretlint/core/src/RuleContext.ts
  packages/@secretlint/core/src/SecretLintSourceCodeImpl.ts
  packages/@secretlint/core/src/helper/invariant.ts
  packages/@secretlint/core/src/helper/promise-event-emitter.ts
  packages/@secretlint/core/src/index.ts
  yarn.lock
Labels: Type: Refactoring
