Repository secretlint/secretlint, pull requests merged in 2025-05, with the labels that each got.

#1018 chore(deps): remove try-resolve
  packages/@secretlint/config-loader/package.json
  packages/@secretlint/formatter/package.json
  yarn.lock
Labels: Type: Maintenance

#1034 chore: update lint-staged from v13 to v16
  package.json
  yarn.lock
Labels: dependencies

#1033 refactor: refactor for loop syntax & import multiple times
  packages/@secretlint/config-loader/src/package-name-util.ts
  packages/@secretlint/secretlint-rule-aws/src/index.ts
  packages/@secretlint/secretlint-rule-azure/src/index.ts
Labels: Type: Refactoring

#1038 Add missing `ghu` to typeMap and fix description
  packages/@secretlint/secretlint-rule-github/src/index.ts
Labels: Type: Bug

#1043 chore: update istextorbinary from v6 to v9
  packages/@secretlint/source-creator/package.json
  packages/@secretlint/source-creator/src/index.ts
  yarn.lock
Labels: Type: Dependencies
