Repository secretlint/secretlint, pull requests merged in 2025-06, with the labels that each got.

#1049 Private key rule should enforce correct end private key footer
  packages/@secretlint/secretlint-rule-preset-canary/test/snapshots/secretlint-rule-gcp/ng.privatekey-json/output.json
  packages/@secretlint/secretlint-rule-preset-recommend/test/snapshots/secretlint-rule-gcp/ng.privatekey-json/output.json
  packages/@secretlint/secretlint-rule-privatekey/src/index.ts
Labels: Type: Bug

#1070 🚨 BREAKING CHANGE: Drop Node.js 18 support, add Node.js 20-22 support
  .github/workflows/benchmark.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  README.md
  docs/secretlint-rule.md
  packages/@secretlint/config-creator/package.json
  packages/@secretlint/config-loader/package.json
  packages/@secretlint/core/package.json
  packages/@secretlint/formatter/package.json
  packages/@secretlint/messages-to-markdown/package.json
  packages/@secretlint/node/package.json
  packages/@secretlint/quick-start/package.json
  packages/@secretlint/secretlint-rule-aws/package.json
  packages/@secretlint/secretlint-rule-azure/package.json
  packages/@secretlint/secretlint-rule-basicauth/package.json
  packages/@secretlint/secretlint-rule-example/package.json
  packages/@secretlint/secretlint-rule-filter-comments/package.json
  packages/@secretlint/secretlint-rule-gcp/package.json
  packages/@secretlint/secretlint-rule-github/package.json
  packages/@secretlint/secretlint-rule-internal-test-cjs/package.json
  packages/@secretlint/secretlint-rule-internal-test-esm/package.json
  packages/@secretlint/secretlint-rule-no-dotenv/package.json
  packages/@secretlint/secretlint-rule-no-homedir/package.json
  packages/@secretlint/secretlint-rule-no-k8s-kind-secret/package.json
  packages/@secretlint/secretlint-rule-npm/package.json
  packages/@secretlint/secretlint-rule-pattern/package.json
  packages/@secretlint/secretlint-rule-preset-canary/package.json
  packages/@secretlint/secretlint-rule-preset-recommend/package.json
  packages/@secretlint/secretlint-rule-privatekey/package.json
  packages/@secretlint/secretlint-rule-secp256k1-privatekey/package.json
  packages/@secretlint/secretlint-rule-sendgrid/package.json
  packages/@secretlint/secretlint-rule-slack/package.json
  packages/@secretlint/source-creator/package.json
  packages/@secretlint/tester/package.json
  packages/@secretlint/types/package.json
  packages/secretlint/package.json
  publish/docker/Dockerfile
Labels: Type: Breaking Change

#1072 feat: add @secretlint/secretlint-rule-anthropic for detecting Anthropic Claude API keys
  packages/@secretlint/secretlint-rule-anthropic/LICENSE
  packages/@secretlint/secretlint-rule-anthropic/README.md
  packages/@secretlint/secretlint-rule-anthropic/package.json
  packages/@secretlint/secretlint-rule-anthropic/src/index.ts
  packages/@secretlint/secretlint-rule-anthropic/test/index.test.ts
  packages/@secretlint/secretlint-rule-anthropic/test/snapshots/ng.secret/input.txt
  packages/@secretlint/secretlint-rule-anthropic/test/snapshots/ng.secret/output.json
  packages/@secretlint/secretlint-rule-anthropic/test/snapshots/ok.valid/input.txt
  packages/@secretlint/secretlint-rule-anthropic/test/snapshots/ok.valid/output.json
  packages/@secretlint/secretlint-rule-anthropic/tsconfig.json
  packages/@secretlint/secretlint-rule-preset-canary/package.json
  packages/@secretlint/secretlint-rule-preset-canary/src/index.ts
  packages/@secretlint/secretlint-rule-preset-canary/test/snapshots/secretlint-rule-anthropic/ng.secret/input.txt
  packages/@secretlint/secretlint-rule-preset-canary/test/snapshots/secretlint-rule-anthropic/ng.secret/output.json
  packages/@secretlint/secretlint-rule-preset-canary/test/snapshots/secretlint-rule-anthropic/ok.valid/input.txt
  packages/@secretlint/secretlint-rule-preset-canary/test/snapshots/secretlint-rule-anthropic/ok.valid/output.json
  yarn.lock
Labels: Type: New Rule
