Repository secretlint/secretlint, pull requests merged in 2025-04, with the labels that each got.

#995 test(secretlint): fix --version test
  packages/secretlint/test/cli.test.ts
  packages/secretlint/test/snapshots/--version/options.ts
  packages/secretlint/test/snapshots/--version/output.json
Labels: Type: Testing

#994 Apply new regex pattern to secretlint-rule-openai
  packages/@secretlint/secretlint-rule-openai/src/index.ts
  packages/@secretlint/secretlint-rule-openai/test/snapshots/ng.secret/input.txt
  packages/@secretlint/secretlint-rule-openai/test/snapshots/ng.secret/output.json
  packages/@secretlint/secretlint-rule-openai/test/snapshots/ok.valid/input.txt
  packages/@secretlint/secretlint-rule-openai/test/snapshots/ok.valid/output.json
Labels: Type: Feature

#1007 hotfix: secretlint --version returning 1.0.0
  packages/@secretlint/messages-to-markdown/src/cli.ts
  packages/@secretlint/resolver/src/index.ts
  packages/@secretlint/resolver/test/index.test.ts
  packages/secretlint/src/cli.ts
Labels: Type: Bug
